stages:
  - install
  - build
  - test
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:16
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  image: node:16
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: node:16
  script:
    - npm test

deploy:
  stage: deploy
  image: node:16
  script:
    - echo "Deploy step goes here"
  only:
    - main
